### PR TITLE
Upgrade to Android Gradle Plugin 3.3.1

### PR DESCRIPTION
**Pull request by feiyunw**
Upgrade to Android Gradle Plugin 3.3.1, Gradle 4.10.3, Android SDK build tools 28.0.3 and NDK r15c.

### CODE REVIEW

**Comment by StoddardOXC** [comment]
I am curious why google() is above jcenter() in build.gradle/buildscript/repositories here.

**Comment by StoddardOXC** [comment]
If you are on oxc forums or any relevant discord server, please contact me.
f/ex https://discord.gg/Getkzx

**Comment by feiyunw** [comment]
google() is above jcenter() because that's what I got when I created a new JNI project with Android Studio, and I'd like them in alphabetical order.
BTW I can't reach you via the discord server because of the GFW.

**Comment by StoddardOXC** [comment]
Hm strange, I very much remember that they wrote somewhere that the order matters. But whatever, maybe it's for older gradles or something.

Please up the versions to the latest possible while keeping support for target android as low as possible.
Keeping target at most at r14 while upgrading to gradle 5 and latest sdk/ndk will be much appreciated.

We're very short on android experts, so your help is very welcome.

What's the GFW?

**Comment by StoddardOXC** [comment]
Ah now I see what's the GFW is. 

We've merged the gradle/sdk/ndk update, many thanks for pointing this out.
Also yaml-cpp was updated and boost was dropped and it should all be much better now.

Thank you very much for this. Unfortunately it wasn't possible to accept your PR as is, which is why I asked for more communication.

If you're interested in helping us, let's keep contact via my email at stoddard@lxnt.info. I'm sure we'll be able to set up something to chat, which is essential.

**Comment by feiyunw** [comment]
I chose NDK r15c because it comes with the VS2017 offline installation that I regularly update.
Other NDK versions present in VS2017 are r13b, r12b and r11c, but r14 is absent for some unknown reason.

**Comment by StoddardOXC** [comment]
Ah, ok. It doesn't work with r19b for some reason anyway.

Does the current version work for you (modulo changing the ndk to what you have)?

**Comment by MeridianOXC** [comment]
Already integrated.

**Comment by feiyunw** [comment]
> Ah, ok. It doesn't work with r19b for some reason anyway.
> 
> Does the current version work for you (modulo changing the ndk to what you have)?

I tried the NDK version (19.1.5304403) in sdk-tools-windows\ndk-bundle and it failed.

**Comment by feiyunw** [comment]
FYI, SDL2 requires [Android SDK (version 26 or later)](https://developer.android.com/sdk/index.html), [Android NDK r15c or later](https://developer.android.com/tools/sdk/ndk/index.html) and Minimum API level supported by SDL: 16 (Android 4.1).

See:
http://hg.libsdl.org/SDL/file/0ff5bbe35bf5/docs/README-android.md

**Comment by StoddardOXC** [comment]
It's not that, it builds fine with NDK 18 or 19 without 'b'.

**Pull request closed without merging**
